name: "Aria's Fight"
favicon: null
layout_spectrum: 0.89847
typography_spectrum: 0.62637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e5b9'
    - '#a38da2'
    - '#d78b51'
    - '#e05330'
    - '#e52735'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
