name: "Aria's Fight"
favicon: null
layout_spectrum: 0.89847
typography_spectrum: 0.62637
title: "Aria's fight "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff9d'
    - '#001000'
    - '#08facf'
    - '#198ff8'
    - '#9ea9e9'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
