name: "Aria's Fight"
favicon: null
layout_spectrum: 0.990709
typography_spectrum: 0.87285
title: "Welcome to Aria's Fiht"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020107'
    - '#7e6163'
    - '#caa39c'
    - '#db738e'
    - '#f0d3cd'
  brandStrength: 0.639183932216838
  lightness: 0.4021073179319501
  saturation: 0.5
  rhythmicContrast: 0.4523121777456254
purpose: []
