analytics: {}
color:
  brandColors:
    - '#D8D0B0'
    - '#246060'
    - '#A89878'
    - '#58C0C0'
    - '#F0E8C8'
  brandStrength: 0.75
  lightness: 0
  rhythmicContrast: 0.75
  saturation: 0.625
cta: {}
layout_spectrum: 1
name: "Aria's Fight"
opengraph: {}
purpose: []
typography_spectrum: 0.514358
