analytics: {}
color:
  brandColors:
    - '#A0A0C0'
    - '#6C6C19'
    - '#A09858'
    - '#D0D030'
    - '#000000'
  brandStrength: 0.921453
  lightness: 0.373311
  rhythmicContrast: 0.75
  saturation: 0.625
cta: {}
layout_spectrum: 1
name: "Aria's Fight"
opengraph: {}
purpose: []
typography_spectrum: 0.514358
