name: "Aria's Fight"
favicon: null
layout_spectrum: 0.25039
typography_spectrum: 0.514358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0A8'
    - '#65202A'
    - '#B0A880'
    - '#983040'
    - '#000000'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
