analytics: {}
color:
  brandColors:
    - '#C0D0D8'
    - '#000000'
    - '#787880'
    - '#000000'
    - '#000000'
  brandStrength: 0.806588
  lightness: 0.247466
  rhythmicContrast: 0.75
  saturation: 0.524493
cta: {}
layout_spectrum: 1
name: "Aria's Fight"
opengraph: {}
purpose: []
typography_spectrum: 0.514358
