analytics: {}
color:
  brandColors:
    - '#000000'
    - '#482078'
    - '#8058A8'
    - '#7040A8'
    - '#C088E8'
  brandStrength: 0.806588
  lightness: 0.247466
  rhythmicContrast: 0.75
  saturation: 0.524493
cta: {}
layout_spectrum: 1
name: "Aria's Fight"
opengraph: {}
purpose: []
typography_spectrum: 0.514358
